package com.signakey.sktrack.skclient;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/29/2015 2:45:50 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapSerializationEnvelope;

import java.util.Hashtable;

import org.ksoap2.serialization.SoapObject;

public class MediaFileMatch extends BaseObject implements KvmSerializable {
    
    
    public MediaFileMatch(){}
    
    public MediaFileMatch(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 0;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    public void register(SoapSerializationEnvelope envelope)
    {
        envelope.addMapping(NAMESPACE, "MediaFileMatch", this.getClass());
                
      
         
           
         

    }
}
